### PR TITLE
Redesign

### LINKED ISSUE #79: [IMPROVE] Table of Contents on the side
### Have you read the code of conduct?

- [X] I have read the code of conduct.

### Has this improvement already been suggested?

- [X] My improvement has not been suggested yet.

### Package

blog

### Where can I improve?

It'd be really nice if you didn't have to scroll up every time for the ToC, but instead it was always there on the left side of the screen.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by noClaps**
- [x] I have tested my changes on my device and it is working.
- [x] I am not using insecure packages.
- [x] I am not adding malicious code that may harm the privacy or security of the reader.

Closes #79

### CODE REVIEW

**Review by MesterMan03 — CHANGES_REQUESTED** [review]
It's slightly broken in landscape.
https://github.com/noClaps/blog/assets/48682374/f873eead-b46a-4f62-817b-7e96fb735134
(I'm trying to scroll on the ToC, instead it scrolls the content)

**Review by MesterMan03 — CHANGES_REQUESTED** [review]
image
This design is probably not the best idea for phones, the notes take up too much horizontal space.

image
Landscape mode is still weird. It can be scrolled now, but unless you zoom out (the screenshot was made with normal 100% zoom) it becomes micro size.
I'd suggest something that can be activated by swiping from the left and sits on top of the post, thereby not causing weird size issues.

**Review by MesterMan03 — DISMISSED** [review]
Well it's functional now. It could still use some aesthetic improvements, but they'll come later anyway.

**Comment by noClaps** [comment]
If you have any ideas for designs, let me know

**Review by MesterMan03 — APPROVED** [review]
Very nice new design, I give 👍

**Pull request merged**
